-- [0단계] 숫자 테이블 생성 (MySQL)
--
-- PostgreSQL 의 generate_series(1, n) 를 MySQL 에서 대체하기 위한 보조 테이블.
-- 1 ~ 10000 을 담으며, 이후 시드 스크립트가 이 테이블과 CROSS JOIN 해서 행을 만든다.
--
-- 사용법: 한 번만 실행하면 된다. 멱등(여러 번 돌려도 안전).
-- 정리: DROP TABLE seq_numbers;

CREATE TABLE IF NOT EXISTS seq_numbers (
    n INT PRIMARY KEY
) ENGINE = InnoDB;

INSERT IGNORE INTO seq_numbers (n)
SELECT a.i + b.i * 10 + c.i * 100 + d.i * 1000 + 1
FROM (SELECT 0 i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
      UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
     (SELECT 0 i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
      UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
     (SELECT 0 i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
      UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
     (SELECT 0 i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
      UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d;

-- 확인: 10000 이 나와야 한다
SELECT COUNT(*) AS total, MIN(n) AS min_n, MAX(n) AS max_n FROM seq_numbers;
